# Generated by Django 3.0.2 on 2020-01-07 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_file_url', models.URLField(help_text='文件url', verbose_name='文件url')),
                ('s_file_name', models.CharField(help_text='文件名', max_length=48, verbose_name='文件名')),
                ('s_title', models.CharField(help_text='文件标题', max_length=150, verbose_name='文件标题')),
                ('s_desc', models.TextField(help_text='文件描述', verbose_name='文件描述')),
                ('s_image_url', models.URLField(help_text='封面图片url', verbose_name='封面图片url')),
                ('n_doc_type', models.SmallIntegerField(choices=[(1, 'PDF'), (2, 'WORD'), (3, 'EXCEL'), (4, 'PPT'), (5, 'Other')], verbose_name='文件类型')),
            ],
            options={
                'verbose_name': '文件表',
                'verbose_name_plural': '文件表',
                'db_table': 'doc_list',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('s_password', models.CharField(max_length=20, verbose_name='密码')),
                ('n_phonenumber', models.IntegerField(verbose_name='手机号')),
                ('s_mail', models.EmailField(max_length=30, verbose_name='邮箱')),
            ],
            options={
                'db_table': 'doc_users',
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.SmallIntegerField()),
                ('math', models.SmallIntegerField()),
                ('english', models.SmallIntegerField()),
                ('s_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_privilege', to='sharehw.User', to_field='s_username')),
            ],
            options={
                'db_table': 'doc_privilege',
            },
        ),
    ]
