# Generated by Django 3.0.2 on 2020-01-08 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharehw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doc',
            table='doc_filelist',
        ),
    ]
